# Generated by Django 6.0.6 on 2026-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('percentage', models.PositiveIntegerField()),
                ('icon', models.CharField(blank=True, help_text='Bootstrap Icon Class (e.g. bi bi-filetype-py)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
