# Generated by Django 6.0.6 on 2026-08-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('issued_by', models.CharField(max_length=200)),
                ('issue_date', models.DateField()),
                ('image', models.ImageField(upload_to='certificates/')),
                ('certificate_link', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
